[package]
name = "devboard-presence"
version = "0.1.0"
edition = "2024"

[dependencies]
devboard-domain = { path = "../domain" }
redis = { version = "1", features = [
    "tokio-comp",
    "connection-manager",
    "tokio-rustls-comp",
    "tls-rustls-webpki-roots",
] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
