//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dm_thread")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "idx_dm_thread_org_participants_unique")]
    pub participant_a: Uuid,
    #[sea_orm(unique_key = "idx_dm_thread_org_participants_unique")]
    pub participant_b: Uuid,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(unique_key = "idx_dm_thread_org_participants_unique")]
    pub organization_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dm_message::Entity")]
    DmMessage,
    #[sea_orm(has_many = "super::dm_message_clear::Entity")]
    DmMessageClear,
    #[sea_orm(
        belongs_to = "super::organization::Entity",
        from = "Column::OrganizationId",
        to = "super::organization::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organization,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ParticipantA",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ParticipantB",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User1,
}

impl Related<super::dm_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DmMessage.def()
    }
}

impl Related<super::dm_message_clear::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DmMessageClear.def()
    }
}

impl Related<super::organization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organization.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::dm_message_clear::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::dm_message_clear::Relation::DmThread.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
