//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "event_series")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub organization_id: Uuid,
    pub created_by: Uuid,
    pub title: String,
    pub description: Option<String>,
    pub event_type: String,
    pub audience_type: String,
    pub team_id: Option<Uuid>,
    pub project_id: Option<Uuid>,
    pub location: Option<String>,
    pub meeting_url: Option<String>,
    pub timezone: String,
    pub duration_minutes: i32,
    pub recurrence_kind: String,
    pub interval_days: Option<i32>,
    pub recurrence_end_at: Option<DateTime>,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_attendee::Entity")]
    EventAttendee,
    #[sea_orm(has_many = "super::event_occurrence::Entity")]
    EventOccurrence,
    #[sea_orm(
        belongs_to = "super::organization::Entity",
        from = "Column::OrganizationId",
        to = "super::organization::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organization,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Project,
    #[sea_orm(
        belongs_to = "super::team::Entity",
        from = "Column::TeamId",
        to = "super::team::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Team,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedBy",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::event_attendee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAttendee.def()
    }
}

impl Related<super::event_occurrence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventOccurrence.def()
    }
}

impl Related<super::organization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organization.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_attendee::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_attendee::Relation::EventSeries.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
