//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "project")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "idx_projects_org_key_unique")]
    pub organization_id: Uuid,
    pub team_id: Uuid,
    pub name: String,
    #[sea_orm(unique_key = "idx_projects_org_key_unique")]
    pub key: String,
    pub description: Option<String>,
    pub next_task_number: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "organization_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub organization: HasOne<super::organization::Entity>,
    #[sea_orm(has_many)]
    pub tasks: HasMany<super::task::Entity>,
    #[sea_orm(
        belongs_to,
        from = "team_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub team: HasOne<super::team::Entity>,
    #[sea_orm(has_many, via = "project_membership")]
    pub users: HasMany<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
