//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "idx_tasks_project_number_unique")]
    pub project_id: Uuid,
    #[sea_orm(unique_key = "idx_tasks_project_number_unique")]
    pub task_number: i32,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub status: String,
    pub priority: String,
    pub assignee_id: Option<Uuid>,
    pub reporter_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub comments: HasMany<super::comment::Entity>,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project: HasOne<super::project::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "User2",
        from = "assignee_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub user_2: HasOne<super::user::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "User1",
        from = "reporter_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub user_1: HasOne<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
