//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "team_membership")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub team_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    pub role: String,
    pub joined_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "team_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub team: HasOne<super::team::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
