//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "team")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub organization_id: Uuid,
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "organization_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub organization: HasOne<super::organization::Entity>,
    #[sea_orm(has_many)]
    pub projects: HasMany<super::project::Entity>,
    #[sea_orm(has_many)]
    pub team_memberships: HasMany<super::team_membership::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
