//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub display_name: String,
    pub password_hash: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::channel::Entity")]
    Channel,
    #[sea_orm(has_many = "super::channel_member::Entity")]
    ChannelMember,
    #[sea_orm(has_many = "super::channel_message_clear::Entity")]
    ChannelMessageClear,
    #[sea_orm(has_many = "super::comment::Entity")]
    Comment,
    #[sea_orm(has_many = "super::dm_message::Entity")]
    DmMessage,
    #[sea_orm(has_many = "super::dm_message_clear::Entity")]
    DmMessageClear,
    #[sea_orm(has_many = "super::invitation::Entity")]
    Invitation,
    #[sea_orm(has_many = "super::message::Entity")]
    Message,
    #[sea_orm(has_many = "super::message_reaction::Entity")]
    MessageReaction,
    #[sea_orm(has_many = "super::notification::Entity")]
    Notification,
    #[sea_orm(has_many = "super::notification_preference::Entity")]
    NotificationPreference,
    #[sea_orm(has_many = "super::org_membership::Entity")]
    OrgMembership,
    #[sea_orm(has_many = "super::project_membership::Entity")]
    ProjectMembership,
    #[sea_orm(has_many = "super::push_subscription::Entity")]
    PushSubscription,
    #[sea_orm(has_many = "super::task_attachment::Entity")]
    TaskAttachment,
}

impl Related<super::channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channel.def()
    }
}

impl Related<super::channel_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelMember.def()
    }
}

impl Related<super::channel_message_clear::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelMessageClear.def()
    }
}

impl Related<super::comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comment.def()
    }
}

impl Related<super::dm_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DmMessage.def()
    }
}

impl Related<super::dm_message_clear::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DmMessageClear.def()
    }
}

impl Related<super::invitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invitation.def()
    }
}

impl Related<super::message_reaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MessageReaction.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::notification_preference::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationPreference.def()
    }
}

impl Related<super::org_membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrgMembership.def()
    }
}

impl Related<super::project_membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectMembership.def()
    }
}

impl Related<super::push_subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PushSubscription.def()
    }
}

impl Related<super::task_attachment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskAttachment.def()
    }
}

impl Related<super::dm_thread::Entity> for Entity {
    fn to() -> RelationDef {
        super::dm_message_clear::Relation::DmThread.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::dm_message_clear::Relation::User.def().rev())
    }
}

impl Related<super::message::Entity> for Entity {
    fn to() -> RelationDef {
        super::message_reaction::Relation::Message.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::message_reaction::Relation::User.def().rev())
    }
}

impl Related<super::organization::Entity> for Entity {
    fn to() -> RelationDef {
        super::org_membership::Relation::Organization.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::org_membership::Relation::User.def().rev())
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        super::project_membership::Relation::Project.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::project_membership::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
